- name: Install JRE after apt update
  become: yes
  apt:
    name: 
      - default-jre
    state: present
    update_cache: yes

- name: Import Confluent Repository Public Key
  become: yes
  shell: "wget -qO - https://packages.confluent.io/deb/7.2/archive.key | apt-key add -"

- name: Add Confluent Repository
  template:
    src: "https://packages.confluent.io/clients/deb"
    dest: /etc/apt/sources.list
    owner: kafka
    group: kafka
    mode: 0640
  when: true

- name: Update Schema Registry
  apt:
    update_cache: yes

- name: Install Schema Registry
  apt:
    name: confluent-platform
    state: present


