- name: Install JRE after apt update
  become: yes
  apt:
    name: 
      - default-jre
    state: present
    update_cache: yes

- name: Import Confluent Repository Public Key
  become: yes
  shell: "wget -qO - https://packages.confluent.io/deb/7.2/archive.key | apt-key add -"

- name: Add Confluent Repository
  become: yes
  apt_repository: repo="deb [arch=amd64] https://packages.confluent.io/deb/7.2 stable main"
  state: present

- name: Update Schema Registry
  apt:
    update_cache: yes

- name: Install Schema Registry
  apt:
    name: confluent-platform
    state: present


